### ISSUE TITLE
commands.includes not a function

### ISSUE THREAD

**Issue by tibs245** [sebs/capcoin#1]
Hi,
I am on Fedora 24 with npm 5.0.0 and I have installed your package.

But when I try to use it, it say 
```
/usr/lib/node_modules/capcoin/bin/capcoin:41
if (!commands.includes(program.args[0])) {
              ^

TypeError: commands.includes is not a function
    at Object.<anonymous> (/usr/lib/node_modules/capcoin/bin/capcoin:41:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

Have you an Idea ?

Thank you :)

**Comment by sebs** [comment]
ah npm 5.0 ;) New node ;) I have to look it up and try myself

**Comment by sebs** [comment]
I have checked it. Does not fail for me. However, I added a classic js style needle Hackstack lookup for you. Will release it asaig (as soon as its green)
