### ISSUE TITLE
TypeError: allowed.includes is not a function

### ISSUE THREAD

**Issue by RyanF109** [sebs/capcoin#2]
#:~/capcoin$ capcoin history -t 90day eth --json
/usr/local/lib/node_modules/capcoin/bin/capcoin-history:19
if (!allowed.includes(program.timeframe)) {
             ^

TypeError: allowed.includes is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/capcoin/bin/capcoin-history:19:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by RyanF109** [comment]
~/capcoin$ capcoin charts -t 1day -t price eth
/usr/local/lib/node_modules/capcoin/bin/capcoin-charts:23
if (!allowed.includes(program.timeframe)) {
             ^

TypeError: allowed.includes is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/capcoin/bin/capcoin-charts:23:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by sebs** [comment]
Hint: Write ETH upper case 

./bin/capcoin history -t 1day ETH
./bin/capcoin charts -t 1day ETH

For the code error: I released 2.2.2 that shoudl fix those. I was not working properly when trying to fix this first.
